### Refreshing Python Knowledge

In [34]:
10*1e3

10000.0

In [26]:
3**3**2

19683

In [5]:
ta={x for x in range(1,10+1,2)}
tb={x for x in range(1,10+1,2)}
print(ta.difference(tb),ta.union(tb),type(ta))

In [3]:
fd={1:'Khurram',2:'Ayesha',3:"Emaan",4:"Abdullah",5:"Abdulrafay"}
fd[6]='Fatma'
print(fd.keys(), fd.values(),sep="\n")
for i,j in fd.items():
    print(i,j)


dict_keys([1, 2, 3, 4, 5, 6])
dict_values(['Khurram', 'Ayesha', 'Emaan', 'Abdullah', 'Abdulrafay', 'Fatma'])
1 Khurram
2 Ayesha
3 Emaan
4 Abdullah
5 Abdulrafay
6 Fatma


In [53]:
i=5
for i in range(2):
    print ("Loop:i",i)
else:
        print ('Its else')

Loop:i 0
Loop:i 1
Its else


In [66]:
print(2*2)
print("Shifting left side = Multiplication:", 2<<2) #Shifting left side = Multiplication
print("Shifting right side = Division:", 20>>2) #Shifting right side = Division
print("Bitwise OR left side:", 2|4) #Bitwise OR left side

4
Shifting left side = Multiplication: 8
Shifting right side = Division: 5
Bitwise OR left side: 6


In [77]:
dc1=['1','2','4K','4.5','A','a']
print(max(dc1),tochar(97)

SyntaxError: unexpected EOF while parsing (<ipython-input-77-82959e12df29>, line 2)

In [82]:
var=1
while var>=1:
    print("Inside loop")
    var=++var
    break
else:
    print("Outside loop")

Inside loop


In [113]:
lst=[1,2,3,4,5,6,7]
nlst=lst[2:5]
nlst=lst[::-1]
nlst=lst[:]
nlst.remove(7) #Remove 1st occurance of data i.e. 7
print("Remove 1st occurance of data i.e. 7:",nlst)
del nlst[5]
print("Del by index i.e. 5:",nlst)
nlst.pop()
print("Pop by index i.e. last item:",nlst)
nlst.pop(0)
print("Pop by index i.e. 1-specified index:",nlst)

Remove 1st occurance of data i.e. 7: [1, 2, 3, 4, 5, 6]
Del by index i.e. 5: [1, 2, 3, 4, 5]
Pop by index i.e. last item: [1, 2, 3, 4]
Pop by index i.e. 1-specified index: [2, 3, 4]


In [120]:
lst=[1,2,3,4,5,6,7]
nlst=lst
del nlst[:]
print("List",nlst, lst)

List [] []


In [127]:
Board=[]
for i in range(8):
    row=["*" for i in range(8)]
    Board.append(row)
print(Board)

[['*', '*', '*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*', '*', '*']]


In [141]:
import numpy as np
x=np.ones((8,8))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
b=[]
row=["*" for i in range(8)]

for i in range(8):
    b.append(row)
b

[['*', '*', '*', '*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*', '*', '*', '*']]

In [127]:
from random import random,sample
class Hashtable():
    def __init__(self):
        self.size=100
        self.arr=['' for x in range(1,100+1)]
    def hashfun(self,h_key):
        return (self.size%len(h_key))
    def setv(self,val):
        ari=self.hashfun(val)
        print("Index:",ari)
        self.arr[ari]=val
        print(self.arr)
##
hashmap=Hashtable()
print(hashmap.setv('khurram'))

    
        
    
        

Index: 2
['', '', 'khurram', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
None


In [55]:
a=int(input("Please enter an int:"))

sqrt=lambda a:a**2
print("SQRT:",sqrt(a))
#


Please enter an int:6
SQRT: 36


In [93]:
from random import sample
ls=[1,2,3]
print(sample([1,2,3,4,5,6],2))    
print(ord('a'))
print(ord('A'))
print(chr(98))
print(chr(99))
#

[3, 2]
97
65
b
c
