# Assignment: 01, Python Numpy Functions

# Roll Number:PIAIC105183
# Name: Khurram Nazir

In [18]:
import numpy as np

In [19]:
l=[0,1,2,3,4,5,6,7,8,9]
print("This is normal-Array:",l,"Now printing array with np.array():",np.array(l),sep="\n")


This is normal-Array:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Now printing array with np.array():
[0 1 2 3 4 5 6 7 8 9]


# Generating Odd array

In [50]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

# Reversing an array

In [51]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[::-1,]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# To know the size of an array

In [52]:
lt=[1,5,6,9,8]
arr=np.array(lt)
print("Size:",arr.size)

Size: 5


# The type of Array

In [53]:
import numpy as np
A=(1,5,6,9,8)
print ("Array type:",type(A), "Element 2 of Tupple:",A[1])

arr=np.array((A),dtype=float)
print("Data Type:",arr.dtype)

Array type: <class 'tuple'> Element 2 of Tupple: 5
Data Type: float64


In [54]:
# Dimension of Array

list=[1,5,6,9,8]
arr=np.array(list)
print("Dimensions:",arr.ndim)


Dimensions: 1


In [55]:
#Replace all odd numbers in arr with -1 without changing arr¶

import numpy as np
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [56]:
#Stack arrays a and b horizontally by using

import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a,b)
np.c_[a, b]

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [57]:
# Mean of arrays

import numpy as np
a = np.array([1,2,3])
print("Mean value is :", a.mean())

Mean value is : 2.0


In [68]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,20])
print("Min value is :", np.median(a))

Min value is : 5.5


In [69]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,20])
print("Min value is :", np.std(a))

Min value is : 5.123475382979799


In [71]:
#converting int then to str

import numpy as np
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d.astype('int').astype('str')

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U11')

In [72]:
#Ravel
arr2 = np.arange(1,10)
b2 = arr2.ravel()  
b2[0] = 101  # changing b2 changes arr2 also
arr2

array([101,   2,   3,   4,   5,   6,   7,   8,   9])