### numpy library excercise

In [ ]:
%history

In [12]:
import numpy as np
npa=np.arange(10).reshape(5,2)
print ("numpy array class ist:"," aber type ist:",npa.dtype)
npa

numpy array class ist:  aber type ist: int32


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
import numpy as np
npa=np.array([[1,2,3],[2,5,6]])
npb=npa[(npa+5)>6]
npb

array([ 7,  8,  7, 10, 11])

In [2]:
import numpy as np
npa=np.array([2,5,6,0,88,28,18])
a=npa[npa>2] # Boolean indexsing
b=npa[[1,2,6]] # Fency indexsing
print(np.float_(b))

[ 5.  6. 18.]


In [66]:
import numpy as np
x=np.random.rand(3,6).astype(float)+1
print(np.float_(x),end="\n\n")
print(x[0:2,:2],end="\n\n") #First 2 rows, first 2 columns.
print(x[0:2,:],end="\n\n") #First 2 rows with all columns.
print(x[:,0:-1],end="\n\n")#All rows except last columns.

[[1.28501504 1.42201182 1.08817235 1.08609927 1.21119769 1.45616561]
 [1.96335485 1.54742836 1.72715513 1.1548124  1.83981163 1.75162298]
 [1.2853522  1.79508312 1.9004372  1.62036148 1.73676198 1.03097753]]

[[1.28501504 1.42201182]
 [1.96335485 1.54742836]]

[[1.28501504 1.42201182 1.08817235 1.08609927 1.21119769 1.45616561]
 [1.96335485 1.54742836 1.72715513 1.1548124  1.83981163 1.75162298]]

[[1.28501504 1.42201182 1.08817235 1.08609927 1.21119769]
 [1.96335485 1.54742836 1.72715513 1.1548124  1.83981163]
 [1.2853522  1.79508312 1.9004372  1.62036148 1.73676198]]



In [96]:
import numpy as np
npa=np.ones((5,5))
print(npa,end="\n\n")
npa[1:-1,1:-1]=0
print(np.int_(npa),end="\n\n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]



In [121]:
import numpy as np
npa=np.array([11,2,6,3,0,4])
npa=npa.reshape((3,2,-1))
#print(npa.flatten() )
npa=np.where(npa>1,'YES','No')
print(npa)

[[['YES']
  ['YES']]

 [['YES']
  ['YES']]

 [['No']
  ['YES']]]


In [14]:
import numpy as np
np.random.binomial(5zzzzzzzza,n)

ValueError: p < 0, p > 1 or p is NaN